<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlayerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('players')->insert([
            [
                "name"=>"Gusikowski",
                "surname"=>"Mattie",
                "age"=>"33",
                "phone"=>"+9612846646256",
                "email"=>"janice89@hotmail.com",
                "gender"=>"female",
                "country"=>"French Polynesia",
                "position"=>"front",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Wiegand",
                "surname"=>"Kenna",
                "age"=>"30",
                "phone"=>"+4003885527171",
                "email"=>"stokes.ada@kiehn.com",
                "gender"=>"male",
                "country"=>"Niue",
                "position"=>"front",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Thiel",
                "surname"=>"Guiseppe",
                "age"=>"26",
                "phone"=>"+3953452651576",
                "email"=>"jsporer.chanelle@hotmail.com",
                "gender"=>"female",
                "country"=>"Syrian Arab Republic",
                "position"=>"replace",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Gusikowski",
                "surname"=>"Mattie",
                "age"=>"33",
                "phone"=>"+9612846646256",
                "email"=>"janice89@hotmail.com",
                "gender"=>"female",
                "country"=>"French Polynesia",
                "position"=>"front",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Nitzsche",
                "surname"=>"Jordyn",
                "age"=>"17",
                "phone"=>"+1825424672750",
                "email"=>"ihackett@kovacek.com",
                "gender"=>"male",
                "country"=>"Belgium",
                "position"=>"back",
                "team_id"=>"1",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Carroll",
                "surname"=>"Berniece",
                "age"=>"30",
                "phone"=>"+1327324054522",
                "email"=>"pauline.welch@hotmail.com",
                "gender"=>"female",
                "country"=>"Canada",
                "position"=>"center",
                "team_id"=>"3",
                "photo_id"=>"1"
            ],
            [
                "name"=>"West",
                "surname"=>"Simeon",
                "age"=>"33",
                "phone"=>"+6826821688968",
                "email"=>"sunny05@yahoo.com",
                "gender"=>"male",
                "country"=>"Finland",
                "position"=>"front",
                "team_id"=>"4",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Rosenbaum",
                "surname"=>"Noemie",
                "age"=>"18",
                "phone"=>"+9557939326892",
                "email"=>"florence46@hintz.biz",
                "gender"=>"female",
                "country"=>"Moldova",
                "position"=>"replace",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Collier",
                "surname"=>"Forrest",
                "age"=>"36",
                "phone"=>"+5672299425154",
                "email"=>"rosanna57@borer.com",
                "gender"=>"male",
                "country"=>"Thailand",
                "position"=>"center",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Abernathy",
                "surname"=>"Felicity",
                "age"=>"40",
                "phone"=>"+4156041703837",
                "email"=>"freddy.schiller@yahoo.com",
                "gender"=>"female",
                "country"=>"Aruba",
                "position"=>"front",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Muller",
                "surname"=>"Elenor",
                "age"=>"30",
                "phone"=>"+5455040858363",
                "email"=>"maggio.adrien@hotmail.com",
                "gender"=>"male",
                "country"=>"Mozambique",
                "position"=>"back",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Hettinger",
                "surname"=>"Elton",
                "age"=>"22",
                "phone"=>"+1643249758116",
                "email"=>"mayert.jeramy@yahoo.com",
                "gender"=>"male",
                "country"=>"Russian Federation",
                "position"=>"center",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Parisian",
                "surname"=>"Mathilde",
                "age"=>"31",
                "phone"=>"+9957345307729",
                "email"=>"frederique90@hotmail.com",
                "gender"=>"female",
                "country"=>"Turkey",
                "position"=>"replace",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Thiel",
                "surname"=>"Gina",
                "age"=>"37",
                "phone"=>"+3188880775457",
                "email"=>"pfeffer.korbin@dubuque.net",
                "gender"=>"female",
                "country"=>"Philippines",
                "position"=>"front",
                "team_id"=>"3",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Stamm",
                "surname"=>"Colleen",
                "age"=>"27",
                "phone"=>"+7671948008921",
                "email"=>"xokon@hotmail.com",
                "gender"=>"male",
                "country"=>"Gibraltar",
                "position"=>"center",
                "team_id"=>"",
                "photo_id"=>"1"
            ],
            [
                "name"=>"Bogisich",
                "surname"=>"Marian",
                "age"=>"28",
                "phone"=>"+9652247821656",
                "email"=>"reyes.koss@lakin.com",
                "gender"=>"male",
                "country"=>"Malta",
                "position"=>"back",
                "team_id"=>"",
                "photo_id"=>"1"
            ]
        ]);
    }
}
